### ISSUE TITLE
What about associations ?

### ISSUE THREAD

**Issue by jeremyputeaux** [rfink/sequelize-redis-cache#11]
Hello,
I'm trying to had your lib to my project but i'm facing problem with my differents associations:
http://docs.sequelizejs.com/en/latest/api/associations/

I only get {"status":500,"error":{"code":"MODULE_NOT_FOUND"}}

Is this an issue or am I doing something wrong ?

**Comment by rfink** [comment]
Can you make a plunkr (or similar) to demo the problem?  It was designed to work correctly with associations.  MODULE_NOT_FOUND makes me think you may be missing a dependency.

**Comment by jeremyputeaux** [comment]
Of course.
Hope I forgot nothing and this helps.
https://plnkr.co/edit/bXE9xZYps6LhI11a8ejm

**Comment by rfink** [comment]
Thanks.  Can you also drop in your package.json?

**Comment by jeremyputeaux** [comment]
There you go:
`{
  "name": "fhdjslfhsld",
  "version": "0.0.2",
  "description": "",
  "main": "server.js",
  "author": "Jeremy Puteaux",
  "dependencies": {
    "bcrypt": "*",
    "bluebird": "^3.1.1",
    "body-parser": "*",
    "compression": "*",
    "cors": "*",
    "express": "^5.0.0-alpha.2",
    "express-jwt": "*",
    "express-validator": "^2.18.0",
    "jsonwebtoken": "^5.5.0",
    "pg": "^4.4.3",
    "pg-hstore": "^2.3.2",
    "redis": "^2.5.0-1",
    "sequelize": "^3.18.0",
    "sequelize-hierarchy": "^0.5.8",
    "sequelize-redis-cache": "^1.1.1",
    "sequelize-slugify": "^0.3.0"
  }
}
`

**Comment by rfink** [comment]
Thanks.  I'm going to try to look at this within a few days.  I know some other issues have been raised around this module and Postgres, I may very well be missing something.

**Comment by jeremyputeaux** [comment]
Alright! Thanks for the investigations!

**Comment by rfink** [comment]
No problem, thanks for using the module!

**Comment by rfink** [comment]
So I'm having some trouble with your plunkr, some syntax errors and such.  But I poked around a bit anyway, trying to see what I could find.  Can you try to add "pg-native" to your dependencies and npm install again?  A previous issue seem to have been resolve by adding this module, even though it doesn't seem to be otherwise required.  If it works, I'll add it as a requirement to the README.md, and then after some investigation, if it's required, I'll add it to peerDependencies.

**Comment by rfink** [comment]
Going to close due to inactivity, please reopen if you encounter the issue after adding pg-native.
