### ISSUE TITLE
Allow raw querying via the module

### ISSUE THREAD

**Issue by rfink** [rfink/sequelize-redis-cache#12]
Allow a raw query through the module, in addition to find, findOne, etc.  See branches/feature/new_api

**Comment by gimox** [comment]
+1 for raw query

**Comment by knoxcard** [comment]
+1

**Comment by rfink** [comment]
Hello! Have either of you checked out the branch feature/new_api? Any comments on API design? It would be a slight change from how you interface with it now, but would allow raw querying.

**Comment by knoxcard** [comment]
I will try to read it today or tomorrow!  I'd love to contribute.  In the meantime, I call raw sequelize statements without the redis cache in certain areas of my SaaS application that need up to the minute info.

**Comment by rfink** [comment]
Fixed and released as 2.0.0 (note: backwards incompatible API changes).  Thanks!
