### ISSUE TITLE
Support for findAndCount, perhaps others

### ISSUE THREAD

**Issue by mccloud-jeff** [rfink/sequelize-redis-cache#13]
I needed support for findAndCount, but your dynamically bound list of methods only includes findAndCountAll.

```
var methods = [
  'find',
  'findOne',
  'findAll',
  'findAndCountAll',
  'all',
  'min',
  'max',
  'sum',
  'count'
];
```

I added in `'findAndAcount',`manually and it appears to work as expected.  Is there a reason for excluding this method and/or others?  Could this support be added?  (need a PR?)

Thanks!

**Comment by rfink** [comment]
Hello, I believe when I wrote this, findAndCount wasn't a thing yet.  I could be mistaken, but I don't believe there's any technical limitation leaving it out.  If you'd like to make a PR, that would be great!  Love contributions.  If not, I can make a note to add it.

**Comment by mccloud-jeff** [comment]
OK great, will do a PR soon!

**Comment by rfink** [comment]
This is added in 1.3.0.  Thanks!
