### ISSUE TITLE
put cacheHit to false on fetchFromDatabase. 

### ISSUE THREAD

**Issue by roccomuso** [rfink/sequelize-redis-cache#19]
Perhaps I could be wrong, but looking at the code, If using the same instance of a cacher obj for multiple query, the **cacheHit** var is not put again to false.

Shouldn't we expect a <code>self.cacheHit = false;</code> before L64 https://github.com/rfink/sequelize-redis-cache/blob/master/lib/index.js#L64 ?

**Comment by rfink** [comment]
I believe you are correct, if someone were to re-use a cache instance, this could be a problem.  I'll work on a fix.  Thanks!

**Comment by rfink** [comment]
This is addressed in 1.2.1.  Thanks!
